
# base image and node version
FROM node:10.15

#set working directory
RUN mkdir  /usr/src/app
#copy all files to docker
COPY  . /usr/src/app

WORKDIR /usr/src/app

#add/usr/src/app/node_modules/.bin to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

#install and cache app dependencies
RUN yarn

#start app
CMD ["npm", " start"]